---
DESIGN_NAME: wb_ram
VERILOG_FILES: 
  - rtl/DFFRAM256x32.v
  - rtl/wb_ram.sv
CLOCK_PERIOD: 10
CLOCK_PORT: wb_clk
# Power Distribution Stuff
FP_PDN_VOFFSET: 7
FP_PDN_HOFFSET: 7
FP_PDN_SKIPTRIM: true
RUN_POST_GRT_RESIZER_TIMING: true
RUN_POST_GRT_DESIGN_REPAIR: true
SYNTH_AUTONAME: true